# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-07 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default=datetime.datetime(2019, 7, 7, 8, 56, 6, 186580, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
